### ISSUE TITLE
MMWormhole not receiving messages when the app is launched from glance

### ISSUE THREAD

**Issue by DomJez** [mutualmobile/MMWormhole#69] opened 2015-11-23 15:44 UTC
The library works fine in the main watch application with WatchOS 2. When you go on the application glance and after you tap on the glance to return in the application, MMWormdhole don't receive any message from the iPhone (iOS 9). it's necessary to make a force touch to show the application menu and after, quit the menu to reactivate MMWormhole. After that, it works fine.
This problem exists only on the watch. There is no problem on the simulator.
Any ideas of the problem ?

**Comment by cnstoll** [comment] 2015-11-23 15:46
I've heard about a WatchConnectivity issue that sounds very similar to this. I'm betting this is the root cause. If it is, I'm not sure what we'll be able to do to fix it without an iOS update :(

https://forums.developer.apple.com/thread/14740

**Comment by TaimoorAli-Sematree** [comment] 2015-11-24 10:25
I'm facing some issues. Kindly answer me to fix the issue. On iPhone app side I'm using this

let wormhole : MMWormhole = MMWormhole(applicationGroupIdentifier: "group.com.xyz", optionalDirectory: "ProjectDataDict")
wormhole.passMessageObject("message recieved or not?", identifier: "ProjectData")

Just this code on iPhone side no. And on swift side I am doing this

wormhole = MMWormhole(applicationGroupIdentifier: "group.com.xyz", optionalDirectory: "ProjectDataDict")
 let messageObj = wormhole.messageWithIdentifier("ProjectData")

But it is not giving me any message. Kindly tell me the issue. . .

**Comment by TaimoorAli-Sematree** [comment] 2015-11-24 10:26
1 more thing If i send message can i get the same message after 1 hour or so or it will pass that message just for this time ?
Your reply will give me much hope Man!

**Comment by cnstoll** [comment] 2017-05-22 18:49
I guess I can close this now, since glances were ultimately removed.

**Closed by cnstoll** 2017-05-22 18:49 UTC
