### ISSUE TITLE
MMWormhole does not work when passcode is enabled and iPhone is locked

### ISSUE THREAD

**Issue by radianttap** [mutualmobile/MMWormhole#31] opened 2015-05-09 07:50 UTC
I'm using MMWormhole in my Watch app. My Watch does not have passcode, iPhone 5s does have it set. Messages are being passed around ok while the phone is unlocked and for some period after the screen goes off.

After few minutes, it just stops and no data come in. I debugged it in and seems that iOS (8.3) cuts off access to the archive files. This `data` in

```objective-c
NSData *data = [NSData dataWithContentsOfFile:[self filePathForIdentifier:identifier]];
```

in `messageObjectFromFileWithIdentifier:` is always nil. As soon as I unlock the phone, then it returns the data properly. 

Anyone knows a solution to this? I don't know if this is "working by design" or is some tightened security in 8.3, but it pretty much renders MMWormhole not usable for watch apps.

**Comment by cnstoll** [comment] 2015-05-11 15:06
Hola,

This isn't a problem that I've yet experienced. I have a passcode on my iPhone running 8.3, as well as on my watch for that matter, and I used several MMWormhole-driven WatchKit apps (Runtime and Overcast) yesterday while I was out for a run, and both of them worked fine while my phone was locked and out of sight.

I could potentially see an issue here with the default protection value of writing files, which is NSFileProtectionCompleteUntilFirstUserAuthentication. That means that the app wouldn't have access to files until the user has entered their passcode or otherwise unlocked their phone for the "first" time. After that though, everything should continue to work normally. I view that as expected behavior of MMWormhole though. I think most users would expect their data to be protected the same way it is in other apps, and I wouldn't really want to change that from the default value.

I could see exposing a way for developers to change that behavior by specifying a different protection value on NSFileManager, but I wouldn't want to completely change the way MMWormhole works in order to address this.

Thanks,

- Conrad

**Comment by cnstoll** [comment] 2015-05-12 17:56
I don't really see an obvious way of specifying a different protection value when writing to disk. If we were going to do that at all, I think the way to go about it would be to enable it through subclassing, but that would still involve significant changes to the public API that I'm hesitant to do just for this. I'm going to close this for now, but if people think this is something they really want to see feel free to comment or open a new issue with a proposal for what you'd like to see implemented.

**Comment by anlaital** [comment] 2015-05-13 04:18
@cnstoll This is still very much an issue. The current implementation is using the default file system attributes, which include NSFileProtectionKey set to NSFileProtectionComplete. This makes it impossible to write new data in response to, for example, background fetches, when the device is locked. 

Fixing this is trivial, especially when using the recommended pattern of specifying ```optionalDirectory```, as file protection can only be removed from that directory. It is currently possible to hack around this issue by manually setting NSFileProtectionKey to NSFileProtectionCompleteUntilFirstUserAuthentication for that directory, but a cleaner solution would be to offer an API to do that in MMWormhole.

**Comment by anlaital** [comment] 2015-05-13 04:29
https://github.com/mutualmobile/MMWormhole/blob/master/Source/MMWormhole.m#L129

This is another problem. It's using an auxiliary file to atomically write the contents of the NSData to the filesystem. By and of itself this is correct, as you don't want to end up with corrupted data in case the device crashes mid-write, but the file protection of the auxiliary file is a problem when the device is locked.

This can be fixed by using ```(BOOL)writeToFile:(NSString *)path options:(NSDataWritingOptions)writeOptionsMask error:(NSError **)errorPtr``` instead and passing ```NSFileProtectionCompleteUntilFirstUserAuthentication | NSDataWritingAtomic``` to ```writeOptionsMask```.

There definitely should be a setting to control this in MMWormhole.

**Comment by cnstoll** [comment] 2015-05-13 13:40
Point taken @anlaital. I agree it's worth addressing. What do you think about adding a NSDataWritingOptions optional property to MMWormhole that would be empty by default but would allow you to set additional writing options that would be added to NSDataWritingAtomic when MMWormhole writes the actual message? Does that seem like the cleanest way to address this?

**Comment by anlaital** [comment] 2015-05-14 10:10
I think it'd be enough to just provide a boolean flag for this, such as ```@property (nonatomic, getter=isFileProtectionEnabled) BOOL fileProtectionEnabled``` which defaults to ```YES```. This would control both the optional directory ```NSFileProtectionKey``` option as well as ```NSDataWritingOptions``` file protection flags.

**Comment by HiddenJester** [comment] 2015-05-14 18:29
I don't think I understand the current problem. It sounds to me like the issue is that `NSFileProtectionComplete` prevents background file accesses, which means that if you're using WatchKit that the parent/host app can't write or process wormhole messages in the `application:handleWatchKitExtensionRequest:reply` handler because the app is running in the background? And I guess if you had any other background processing in your app you'd have the same problem.

I've got both a WatchKit extension and a Today Widget extension in my app and I just confirmed that I can trigger an `openParentApp` on the watch while the phone is locked and the host app will post a message that the widget picks up and processes. So there's some other piece I'm missing that can cause this problem.

**Comment by anlaital** [comment] 2015-05-15 03:32
@HiddenJester You've understood the problem correctly. :)

Why this does not happen to you, I don't know. Do you have data protection enabled on the device?

**Comment by HiddenJester** [comment] 2015-05-15 18:26
Ah! I bet that's it. I don't have the Data Protection entitlement on for my app. I've never used it so I don't know much on the subject, but since it's not on I suspect that `NSFileProtectionComplete` doesn't mean anything in my app. @radianttap do you have the Data Protection entitlement on your app? Perhaps this issue never had to do with pass codes and has always been an interaction between Data Protection and background operation?

I don't think I want Data Protection on in my app (the data is worthless: nothing of personal or commercial interest.) I'm reluctant to turn it on just as a test since it tweaks the app ID and at the moment I'm happy with the way my app is working :-) Can somebody more knowledgeable on the subject confirm this would be the issue? Also, does anybody know if the simulator simulates Data Protection?

**Comment by radianttap** [comment] 2015-05-16 14:07
@HiddenJester I don't have Data Protection on. 

I am following this thread but have yet to try again. For now, I'm just happy it works with NSUserDefaults from my fork – I need to finish up the app before taking a look at this again.

**Comment by cnstoll** [comment] 2015-05-27 20:29
Hey Guys,

Please check out this pull request. I believe that subclassing the default implementation of the MMWormholeFileTransiting implementation would allow you to implement this behavior if you need it.

https://github.com/mutualmobile/MMWormhole/pull/40

Thanks,

- Conrad

**Comment by cnstoll** [comment] 2015-06-02 15:24
Going ahead and closing this issue. The PR that abstracts out file writing has been merged. Please try that out and let me know what you think.

Thanks,

- Conrad

**Closed by cnstoll** 2015-06-02 15:24 UTC
